name: Verify HTML

on:
  push:
    branches:
      - main
      - sharubranch
      - sowmiyabranch
  pull_request:
    branches:
      - main
      - sharubranch
      - sowmiyabranch

jobs:
  verify-html:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Verify HTML file
      run: |
        echo "Checking HTML file content"
        cat << 'EOF' > verify_html.py
        import sys

        def verify_html(file_path):
            expected_content = '''<center>
  <h1>SARUMATHI VASU</h1>
</center>'''

            try:
                with open(file_path, 'r') as file:
                    content = file.read()

                if expected_content in content:
                    print('HTML content is correct.')
                    sys.exit(0)
                else:
                    print('HTML content is incorrect.')
                    sys.exit(1)
            except FileNotFoundError:
                print(f'File {file_path} not found.')
                sys.exit(1)
            except Exception as e:
                print(f'An error occurred: {e}')
                sys.exit(1)

        if __name__ == "__main__":
            verify_html('sharu.html')
        EOF

        python verify_html.py
